on:
  push:
    branches:
      - main

jobs:
  first-job:
   runs-on: ubuntu-lastest

   steps:
     - name: 1. ssh로 접근.
       uses: appleboy/@v1.0.3
       with:
         host: ${{secrets.EC2_HOST}}
         username: ${{secrets.EC2_USERNAME}}
         key: ${{secrets.EC2_PRIVATE_KEY}}
         script-stop: true
         script: |
           cd /home/ubuntu/depoly-pratice
           git pull https://github.com/codingsimul/depoly-pratice.git
           ./gradlew clean build
           sudo fuser -f -n tcp 8080 || true
           nohup java -jar *SNAPSHOT.jar jar > ./outlog.log 2 >&1 &
