on:
  push:
    branches:
      - main

jobs:
  first-job:
   runs-on: ubuntu-latest

   steps:
     - name: 1. ssh로 접근.
       uses: appleboy/ssh-action@v1.0.3
       env:
        APPLICATION: ${{secrets.APPLICATION}}
       with:
         host: ${{secrets.EC2_HOST}}
         username: ${{secrets.EC2_USERNAME}}
         key: ${{secrets.EC2_PRIVATE_KEY}}
         envs: APPLICATION
         script-stop: true
         script: |
           cd /home/ubuntu/depoly-pratice
           git pull origin https://github.com/codingsimul/depoly-pratice.git
           echo "$APPLICATION" > src/main/resources/application.yml
           ./gradlew clean build
           sudo fuser -f -n tcp 8080 || true
           nohup java -jar *SNAPSHOT.jar jar > ./outlog.log 2 >&1 &
